app:
  version: '@project.version@'

server:
  port: 8081

spring:
  application:
    name: actionmonitor
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/action_monitor
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

broker:
  host: localhost
  port: 61616
  username: admin
  password: password

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus,beans,env


